<?php
// PHPsa modules cache file, generated by PHPsa at 2009-10-07 10:59:51

$PHPsa_modules = array();
$PHPsa_module_paths = array();
$PHPsa_path_modules = array();

// BEGIN STATIC
$PHPsa_modules["Home"] = array("url" => "/");
$PHPsa_modules["Home"]["pages"] = array("Home" => "index.php", "Foo" => "foo.php");
$PHPsa_modules["Admin"] = array("url" => "admin/");
$PHPsa_modules["Admin"]["pages"] = array("Home" => "index.php", "Modules" => "modules.php", "Users" => "users.php", "Settings" => "settings.php");
$PHPsa_module_paths['Home'] = "/";
$PHPsa_path_modules[''] = "Home";

$PHPsa_module_paths['Admin'] = "/admin/";
$PHPsa_path_modules['/admin/'] = "Admin";
// END STATIC

$PHPsa_module_order = array('Home', "Logs", 'Admin');

$PHPsa_modules['Logs'] = array("url" => "modules/logs/");
$PHPsa_modules['Logs']['pages'] = array('Home' => 'index.php', 'Viewer' => 'viewer.php');

$PHPsa_module_paths['Logs'] = "/modules/logs/";
$PHPsa_path_modules['/modules/logs/'] = "Logs";


?>
